import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="h-[calc(100dvh)] container flex max-w-2xl flex-col pt-8">
            <Navbar />
            <main className="flex flex-1 flex-col pb-20 pt-40 md:pt-48">
              {children}
            </main>
          </div>
        </ThemeProvider>
        <div className="bg-[url(/assets/noise-bg.png)] opacity-60 dark:opacity-[0.20] inset-0 pointer-events-none fixed z-[99] h-full w-full overflow-hidden" />
      </body>
    </html>
  );
}
