import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { AuroraBackground } from "@/components/ui/aurora-background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
          <AuroraBackground >
        <ThemeProvider attribute="class" defaultTheme="system">
          <div className="h-[calc(100dvh)] container flex max-w-3xl flex-col pt-8">
            <Navbar />
            <main className="flex flex-1 flex-col pb-20 pt-32 md:pt-40">
              {children}
            </main>
          </div>
        </ThemeProvider>
          </AuroraBackground>
      </body>
    </html>
  );
}
